# Generated by Django 4.0.3 on 2023-01-06 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('roll_no', models.IntegerField()),
                ('city', models.CharField(max_length=70)),
                ('marks', models.IntegerField()),
                ('Department', models.CharField(max_length=90)),
                ('pass_date', models.DateField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
